import jsPDF from 'jspdf';

interface PdfGenerationOptions {
  position: string;
  companyName: string;
  content: string;
}

export const generateCoverLetterPDF = (options: PdfGenerationOptions): string => {
  const { position, companyName, content } = options;
  
  // Create a new PDF document
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  // Set document properties
  doc.setProperties({
    title: `Cover Letter for ${position} at ${companyName}`,
    subject: 'Job Application Cover Letter',
    author: 'AI Cover Letter Generator',
    keywords: 'cover letter, job application',
    creator: 'AI Cover Letter Generator'
  });
  
  // Set fonts and margins
  const margin = 20; // 20mm margins
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - (margin * 2);
  
  // Add current date
  const today = new Date();
  const dateString = today.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(dateString, pageWidth - margin - doc.getTextWidth(dateString), margin + 5);
  
  // Add header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  const title = `Cover Letter: ${position} at ${companyName}`;
  doc.text(title, margin, margin + 15);
  
  // Add a separator line
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.2);
  doc.line(margin, margin + 20, pageWidth - margin, margin + 20);
  
  // Set up cover letter content formatting
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  
  // Format and add the cover letter text with proper line spacing
  const letterContent = content.trim();
  const splitText = doc.splitTextToSize(letterContent, contentWidth);
  doc.text(splitText, margin, margin + 30);
  
  // Add footer with page number
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    const footerText = `Generated by AI Cover Letter Generator - Page ${i} of ${pageCount}`;
    doc.text(
      footerText,
      pageWidth - margin - doc.getTextWidth(footerText),
      doc.internal.pageSize.getHeight() - 10
    );
  }
  
  // Generate filename
  let fileName = 'Cover_Letter';
  if (position && companyName) {
    fileName = `Cover_Letter_${companyName.replace(/\s+/g, '_')}_${position.replace(/\s+/g, '_')}`;
  } else if (position) {
    fileName = `Cover_Letter_${position.replace(/\s+/g, '_')}`;
  } else if (companyName) {
    fileName = `Cover_Letter_${companyName.replace(/\s+/g, '_')}`;
  }
  fileName += '.pdf';
  
  // Save the PDF
  doc.save(fileName);
  
  return fileName;
}; 